In [1]:
import ipyparallel as ipp

In [2]:
client = ipp.Client()

In [3]:
client.ids

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
dview = client[:] 

In [5]:
dview.block = True

## Pushing and pulling data

In [6]:
dview.push(dict(a=3.14, b=2.89))

[None, None, None, None, None, None, None, None, None, None]

In [7]:
dview.pull(('a', 'b'))

[[3.14, 2.89],
 [3.14, 2.89],
 [3.14, 2.89],
 [3.14, 2.89],
 [3.14, 2.89],
 [3.14, 2.89],
 [3.14, 2.89],
 [3.14, 2.89],
 [3.14, 2.89],
 [3.14, 2.89]]

In [8]:
def summing():
    return a + b

In [9]:
dview.apply(summing)

[6.03, 6.03, 6.03, 6.03, 6.03, 6.03, 6.03, 6.03, 6.03, 6.03]

Remote function

In [10]:
@dview.remote(block=True)
def remote_function():
    import numpy as np
    return np.exp(10)

In [11]:
remote_function()

[22026.465794806718,
 22026.465794806718,
 22026.465794806718,
 22026.465794806718,
 22026.465794806718,
 22026.465794806718,
 22026.465794806718,
 22026.465794806718,
 22026.465794806718,
 22026.465794806718]

## Scatter and gather

In [12]:
dview.scatter('a', range(50))
dview.scatter('b', range(50))

In [13]:
dview['a']

[[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24],
 [25, 26, 27, 28, 29],
 [30, 31, 32, 33, 34],
 [35, 36, 37, 38, 39],
 [40, 41, 42, 43, 44],
 [45, 46, 47, 48, 49]]

In [14]:
def summing():
    return np.array(a) + np.array(b)

In [15]:
dview.apply(summing)

[array([0, 2, 4, 6, 8]),
 array([10, 12, 14, 16, 18]),
 array([20, 22, 24, 26, 28]),
 array([30, 32, 34, 36, 38]),
 array([40, 42, 44, 46, 48]),
 array([50, 52, 54, 56, 58]),
 array([60, 62, 64, 66, 68]),
 array([70, 72, 74, 76, 78]),
 array([80, 82, 84, 86, 88]),
 array([90, 92, 94, 96, 98])]

## Magic commands

In [16]:
%%px
a = 10

In [17]:
dview.gather('a')

[10, 10, 10, 10, 10, 10, 10, 10, 10, 10]

In [18]:
%%px --noblock
import numpy as np
a = np.random.rand(100)

<AsyncResult: execute>

In [19]:
%pxresult

In [20]:
dview.pull('a')

[array([0.06359125, 0.3671332 , 0.49484923, 0.01128916, 0.42257526,
        0.02786866, 0.91009854, 0.47366425, 0.85915674, 0.37135062,
        0.07065023, 0.64416689, 0.97060847, 0.99385409, 0.15804307,
        0.77391403, 0.63721697, 0.90486329, 0.0329975 , 0.90382824,
        0.58226354, 0.94618968, 0.14143113, 0.23896884, 0.01764698,
        0.56456638, 0.35615338, 0.10241944, 0.39747538, 0.44808042,
        0.77089006, 0.7455576 , 0.83837969, 0.70585386, 0.56826495,
        0.49674722, 0.8469834 , 0.9596283 , 0.30379102, 0.39901263,
        0.3842355 , 0.04710426, 0.29433737, 0.5092981 , 0.16874534,
        0.17127351, 0.30927262, 0.89178152, 0.28330572, 0.82592225,
        0.29880775, 0.61656566, 0.69130742, 0.75009441, 0.56504075,
        0.91564046, 0.54834615, 0.54435884, 0.40189566, 0.57603876,
        0.05045094, 0.3504737 , 0.61602726, 0.15109671, 0.10536791,
        0.70025036, 0.13323249, 0.78708422, 0.29615578, 0.66086709,
        0.83975922, 0.97516048, 0.35442325, 0.17

In [21]:
%autopx

%autopx enabled


In [22]:
a

Out[0:31]: 
array([0.06359125, 0.3671332 , 0.49484923, 0.01128916, 0.42257526,
       0.02786866, 0.91009854, 0.47366425, 0.85915674, 0.37135062,
       0.07065023, 0.64416689, 0.97060847, 0.99385409, 0.15804307,
       0.77391403, 0.63721697, 0.90486329, 0.0329975 , 0.90382824,
       0.58226354, 0.94618968, 0.14143113, 0.23896884, 0.01764698,
       0.56456638, 0.35615338, 0.10241944, 0.39747538, 0.44808042,
       0.77089006, 0.7455576 , 0.83837969, 0.70585386, 0.56826495,
       0.49674722, 0.8469834 , 0.9596283 , 0.30379102, 0.39901263,
       0.3842355 , 0.04710426, 0.29433737, 0.5092981 , 0.16874534,
       0.17127351, 0.30927262, 0.89178152, 0.28330572, 0.82592225,
       0.29880775, 0.61656566, 0.69130742, 0.75009441, 0.56504075,
       0.91564046, 0.54834615, 0.54435884, 0.40189566, 0.57603876,
       0.05045094, 0.3504737 , 0.61602726, 0.15109671, 0.10536791,
       0.70025036, 0.13323249, 0.78708422, 0.29615578, 0.66086709,
       0.83975922, 0.97516048, 0.35442325, 0.17778

Out[1:31]: 
array([0.62841938, 0.65695191, 0.99555996, 0.46687486, 0.87904416,
       0.25099383, 0.02233693, 0.03178694, 0.20993494, 0.61402734,
       0.6746878 , 0.00849438, 0.49327692, 0.46575766, 0.20746466,
       0.89654203, 0.93304987, 0.33879653, 0.496519  , 0.93597907,
       0.08632203, 0.46813249, 0.88637446, 0.45023615, 0.89403413,
       0.97092305, 0.89265589, 0.33381613, 0.75839799, 0.74227879,
       0.87343626, 0.74266541, 0.55116888, 0.58836015, 0.29220936,
       0.62165947, 0.85487941, 0.46978773, 0.82419488, 0.80363583,
       0.90530523, 0.37323791, 0.96683797, 0.28998254, 0.36052371,
       0.6257325 , 0.43615583, 0.85126685, 0.88509399, 0.52932338,
       0.56238335, 0.93815844, 0.31132326, 0.60375769, 0.61738286,
       0.09353145, 0.06763057, 0.45503621, 0.76639439, 0.05471452,
       0.90661473, 0.3757205 , 0.26227111, 0.20686831, 0.25784475,
       0.20548584, 0.67981663, 0.06776471, 0.10170613, 0.37939253,
       0.17445882, 0.43949652, 0.75839808, 0.72206

Out[2:31]: 
array([0.18358612, 0.66505979, 0.00181493, 0.52990592, 0.07572517,
       0.63339961, 0.11201634, 0.92805021, 0.21567102, 0.48004921,
       0.34515333, 0.59616336, 0.53619346, 0.31612017, 0.26943708,
       0.69738526, 0.86235546, 0.6572444 , 0.90525682, 0.73462168,
       0.34135089, 0.36908582, 0.1341679 , 0.20964725, 0.23474579,
       0.25064221, 0.67332973, 0.21070274, 0.85056732, 0.57645095,
       0.89016241, 0.5572486 , 0.51463342, 0.51207024, 0.85229828,
       0.27603807, 0.2814251 , 0.42003578, 0.73936271, 0.7249531 ,
       0.60418948, 0.58393747, 0.55567459, 0.9705369 , 0.19897597,
       0.33913615, 0.12810737, 0.30293759, 0.16324728, 0.00458912,
       0.7555477 , 0.10453988, 0.81585729, 0.77139628, 0.67928729,
       0.68780186, 0.96439152, 0.89738191, 0.21428635, 0.56271318,
       0.40117285, 0.17714585, 0.48928927, 0.88287716, 0.95787118,
       0.44977524, 0.25590731, 0.64287756, 0.00159031, 0.54601252,
       0.96435886, 0.54362032, 0.70062481, 0.84739

Out[3:31]: 
array([0.28155662, 0.37081535, 0.98875465, 0.34753187, 0.21520277,
       0.79300611, 0.07676626, 0.84701065, 0.95794067, 0.01556601,
       0.31261901, 0.90785053, 0.38833131, 0.39540279, 0.35743177,
       0.22526804, 0.46602663, 0.35977536, 0.58357924, 0.8956353 ,
       0.91522324, 0.51032541, 0.08669201, 0.96546081, 0.42100049,
       0.09874671, 0.05905783, 0.30691356, 0.99243954, 0.02182703,
       0.46920482, 0.74374648, 0.54284787, 0.66000222, 0.61455653,
       0.05836136, 0.29105796, 0.73205605, 0.36146483, 0.33553416,
       0.99161746, 0.87082469, 0.64715378, 0.85230754, 0.28633579,
       0.22701906, 0.00517155, 0.92462325, 0.1005726 , 0.79153109,
       0.58720737, 0.83550141, 0.43146737, 0.59178022, 0.24840112,
       0.87872279, 0.90451683, 0.76854881, 0.59287516, 0.87338416,
       0.3637946 , 0.79502773, 0.56320578, 0.49529085, 0.96771926,
       0.02250408, 0.51028832, 0.33283076, 0.48018873, 0.6405559 ,
       0.08098093, 0.7010844 , 0.81881482, 0.91380

Out[4:31]: 
array([0.33972844, 0.42780079, 0.57002464, 0.73776326, 0.24972182,
       0.90076199, 0.59666472, 0.76265189, 0.79940853, 0.48723454,
       0.78344946, 0.30566064, 0.83040673, 0.11044487, 0.25461066,
       0.36257341, 0.38991006, 0.32678366, 0.60067687, 0.96331621,
       0.5020599 , 0.57431686, 0.38204282, 0.01546562, 0.48790994,
       0.96466679, 0.68251848, 0.70745324, 0.44327579, 0.29886234,
       0.4158756 , 0.41238359, 0.98837088, 0.90399429, 0.74423722,
       0.36408099, 0.25983446, 0.30922439, 0.06000232, 0.80656612,
       0.88240805, 0.64424915, 0.5149028 , 0.53102621, 0.19122533,
       0.79480676, 0.65662858, 0.65318152, 0.26838033, 0.38123604,
       0.08303019, 0.14929497, 0.29068743, 0.00929231, 0.23232744,
       0.15832509, 0.36091744, 0.91538859, 0.39170393, 0.09270566,
       0.39600975, 0.36750419, 0.91324871, 0.00704651, 0.00852111,
       0.25579398, 0.13994732, 0.19633388, 0.43501396, 0.22404116,
       0.17131337, 0.92273226, 0.81367845, 0.90070

Out[5:31]: 
array([0.53136812, 0.58570678, 0.33374212, 0.17285064, 0.91234041,
       0.48121786, 0.27940631, 0.62513648, 0.08755816, 0.61409428,
       0.58708558, 0.91494609, 0.11422199, 0.67659721, 0.21488533,
       0.46135645, 0.71041418, 0.84462756, 0.44575014, 0.69308293,
       0.3702597 , 0.81062534, 0.26457134, 0.71646562, 0.15859096,
       0.82815957, 0.13819408, 0.43977771, 0.28535168, 0.41537747,
       0.25852554, 0.14281913, 0.25051918, 0.47593801, 0.62788575,
       0.83793409, 0.1254385 , 0.16010305, 0.54799756, 0.56418111,
       0.33717944, 0.08614715, 0.59174533, 0.26302445, 0.33154216,
       0.1351078 , 0.89243223, 0.14581785, 0.75913353, 0.65888754,
       0.96570774, 0.998777  , 0.90546266, 0.09447114, 0.37953213,
       0.92646873, 0.85153056, 0.31423422, 0.64175647, 0.55599576,
       0.16674721, 0.84408523, 0.65829241, 0.17304741, 0.807275  ,
       0.91538775, 0.27641109, 0.34203365, 0.37725955, 0.96807383,
       0.80446443, 0.20378123, 0.46886768, 0.22169

Out[6:31]: 
array([0.96224491, 0.51151649, 0.92245739, 0.84530608, 0.87864995,
       0.86850841, 0.45247295, 0.84032383, 0.68810904, 0.92383828,
       0.85990707, 0.64075233, 0.98453689, 0.74806042, 0.06902765,
       0.84182186, 0.42964645, 0.66006794, 0.54670943, 0.13419443,
       0.1049611 , 0.82729484, 0.11998814, 0.24677807, 0.19977996,
       0.1024466 , 0.34992164, 0.0469212 , 0.88666771, 0.05060022,
       0.94445718, 0.80074033, 0.81135431, 0.01264426, 0.50736099,
       0.27377605, 0.46631614, 0.6193176 , 0.33230891, 0.73666879,
       0.44249932, 0.88928263, 0.38816864, 0.18317526, 0.56675239,
       0.11126559, 0.55502548, 0.88443927, 0.95563008, 0.32024547,
       0.03826486, 0.90243341, 0.29757568, 0.33168644, 0.43824761,
       0.13023251, 0.06002586, 0.44837514, 0.47968094, 0.50798382,
       0.44209717, 0.56863306, 0.18588326, 0.66818871, 0.99707576,
       0.7648108 , 0.96496842, 0.97480109, 0.80025531, 0.94940634,
       0.6432809 , 0.14739785, 0.39286887, 0.17502

Out[7:31]: 
array([0.87171403, 0.82810205, 0.43546812, 0.18752473, 0.88349588,
       0.39534839, 0.28972367, 0.08050209, 0.32575592, 0.51673045,
       0.3386332 , 0.56223628, 0.34693403, 0.03073256, 0.50546799,
       0.81052283, 0.99588693, 0.33658138, 0.60412064, 0.83375723,
       0.20442142, 0.21898093, 0.36493999, 0.25157171, 0.32608816,
       0.51631481, 0.348106  , 0.82412523, 0.70205203, 0.92651349,
       0.95718342, 0.56881021, 0.93525696, 0.48773663, 0.35717928,
       0.26514076, 0.2662575 , 0.39318301, 0.50368407, 0.29822576,
       0.61935855, 0.99558951, 0.80100519, 0.09863329, 0.68987398,
       0.21975529, 0.87805681, 0.46792227, 0.04867064, 0.03483954,
       0.44845406, 0.65383457, 0.30887349, 0.66112772, 0.94817334,
       0.26005642, 0.46613028, 0.61007669, 0.55160838, 0.67365198,
       0.17374399, 0.85593833, 0.23497052, 0.35454027, 0.50435273,
       0.75648483, 0.43270902, 0.13332253, 0.66114601, 0.78048754,
       0.64252742, 0.07326874, 0.16642755, 0.33740

Out[8:31]: 
array([0.81797929, 0.64683418, 0.11672064, 0.42771015, 0.44463108,
       0.67931233, 0.99361542, 0.37327966, 0.72441559, 0.87460311,
       0.27159815, 0.81199389, 0.24825686, 0.03154058, 0.59656492,
       0.51692904, 0.43005408, 0.33476343, 0.11630505, 0.37117249,
       0.76037372, 0.94635819, 0.89151991, 0.95602769, 0.02583156,
       0.50205745, 0.39755138, 0.35847352, 0.22290633, 0.54785225,
       0.26074032, 0.64885156, 0.8569144 , 0.86816848, 0.46848666,
       0.06022049, 0.53055034, 0.13164818, 0.07531517, 0.66583115,
       0.74716598, 0.72251318, 0.54281757, 0.91559574, 0.57181492,
       0.47927059, 0.6291903 , 0.94623723, 0.75084545, 0.97510472,
       0.81451365, 0.58552233, 0.87342275, 0.32611718, 0.73891347,
       0.43048256, 0.64100509, 0.91350447, 0.9601835 , 0.27905878,
       0.46602072, 0.596381  , 0.49561037, 0.24386625, 0.76756525,
       0.44156189, 0.77805446, 0.18908164, 0.72829101, 0.71113427,
       0.91129803, 0.19741144, 0.66297379, 0.55669

Out[9:31]: 
array([0.78225021, 0.50067164, 0.1113566 , 0.44709128, 0.7419593 ,
       0.51439133, 0.50080569, 0.98003984, 0.16486823, 0.6356713 ,
       0.11990897, 0.4597787 , 0.74956829, 0.79975744, 0.93942574,
       0.70943081, 0.45145422, 0.93369653, 0.61034072, 0.3478747 ,
       0.76629804, 0.54317769, 0.46606673, 0.57335721, 0.86044341,
       0.39849799, 0.41346198, 0.62163077, 0.83133507, 0.76862079,
       0.70867349, 0.99260424, 0.76178716, 0.61959138, 0.7773359 ,
       0.11253811, 0.19662284, 0.31585564, 0.36755966, 0.3695082 ,
       0.32196058, 0.76270673, 0.5342846 , 0.09272983, 0.23449863,
       0.20847462, 0.20342892, 0.22359519, 0.48615515, 0.37234421,
       0.1872708 , 0.87199622, 0.27600724, 0.9152155 , 0.35161154,
       0.0619041 , 0.10774601, 0.20138682, 0.0364719 , 0.28641923,
       0.49656969, 0.90784797, 0.42684089, 0.37920319, 0.91671248,
       0.0127588 , 0.16624712, 0.18073364, 0.15985684, 0.51407244,
       0.79023112, 0.96244194, 0.60342464, 0.34351

In [23]:
a = 20 

In [24]:
b = 100

In [25]:
%autopx

%autopx disabled


In [26]:
%pxresult

In [27]:
dview.pull('a')

[20, 20, 20, 20, 20, 20, 20, 20, 20, 20]