In [1]:
import ipyparallel as ipp

In [3]:
client = ipp.Client()

In [4]:
client.ids

[0, 1, 2, 3]

In [5]:
dview = client[:] 

In [6]:
dview.block = True

## Pushing and pulling data

In [7]:
dview.push(dict(a=3.14, b=2.89))

[None, None, None, None]

In [8]:
dview.pull(('a', 'b'))

[[3.14, 2.89], [3.14, 2.89], [3.14, 2.89], [3.14, 2.89]]

In [9]:
def summing():
    return a + b

In [11]:
dview.apply(summing)

[6.03, 6.03, 6.03, 6.03]

Remote function

In [12]:
@dview.remote(block=True)
def remote_function():
    import numpy as np
    return np.exp(10)

In [13]:
remote_function()

[22026.465794806718,
 22026.465794806718,
 22026.465794806718,
 22026.465794806718]

## Scatter and gather

In [14]:
dview.scatter('a', range(50))
dview.scatter('b', range(50))

In [15]:
dview['a']

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
 [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
 [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37],
 [38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]

In [18]:
def summing():
    import numpy as np
    return np.array(a) + np.array(b)

In [19]:
dview.apply(summing)

[array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24]),
 array([26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]),
 array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74]),
 array([76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])]

## Magic commands

In [20]:
%%px
a = 10

In [21]:
dview.gather('a')

[10, 10, 10, 10]

In [22]:
%%px --noblock
import numpy as np
a = np.random.rand(100)

<AsyncResult: execute>

In [23]:
%pxresult

In [24]:
dview.pull('a')

[array([0.43563629, 0.0551233 , 0.45436188, 0.44988103, 0.52064309,
        0.25004363, 0.98304875, 0.59306324, 0.09611928, 0.2170223 ,
        0.71756146, 0.98069634, 0.04961027, 0.29676884, 0.88539371,
        0.02844324, 0.36719213, 0.20871957, 0.66134678, 0.70159047,
        0.81558399, 0.47978135, 0.41246282, 0.50158268, 0.25148204,
        0.24907602, 0.37086402, 0.74421762, 0.48998545, 0.23377774,
        0.36497712, 0.51671059, 0.94007832, 0.66887743, 0.61629885,
        0.42432521, 0.60975056, 0.66726426, 0.53401314, 0.11478798,
        0.07367067, 0.22115571, 0.65768979, 0.58425146, 0.34856456,
        0.11635774, 0.8989019 , 0.08021261, 0.32846062, 0.32211953,
        0.9641831 , 0.08161329, 0.12509606, 0.8866671 , 0.49038451,
        0.21920611, 0.43962393, 0.38373017, 0.89578779, 0.08903067,
        0.4165474 , 0.51114294, 0.67038372, 0.55314734, 0.00210258,
        0.41026381, 0.49836006, 0.48029863, 0.42631951, 0.09011671,
        0.40183698, 0.13731001, 0.78305494, 0.16

In [25]:
%autopx

%autopx enabled


In [26]:
a

Out[0:3]: 
array([0.43563629, 0.0551233 , 0.45436188, 0.44988103, 0.52064309,
       0.25004363, 0.98304875, 0.59306324, 0.09611928, 0.2170223 ,
       0.71756146, 0.98069634, 0.04961027, 0.29676884, 0.88539371,
       0.02844324, 0.36719213, 0.20871957, 0.66134678, 0.70159047,
       0.81558399, 0.47978135, 0.41246282, 0.50158268, 0.25148204,
       0.24907602, 0.37086402, 0.74421762, 0.48998545, 0.23377774,
       0.36497712, 0.51671059, 0.94007832, 0.66887743, 0.61629885,
       0.42432521, 0.60975056, 0.66726426, 0.53401314, 0.11478798,
       0.07367067, 0.22115571, 0.65768979, 0.58425146, 0.34856456,
       0.11635774, 0.8989019 , 0.08021261, 0.32846062, 0.32211953,
       0.9641831 , 0.08161329, 0.12509606, 0.8866671 , 0.49038451,
       0.21920611, 0.43962393, 0.38373017, 0.89578779, 0.08903067,
       0.4165474 , 0.51114294, 0.67038372, 0.55314734, 0.00210258,
       0.41026381, 0.49836006, 0.48029863, 0.42631951, 0.09011671,
       0.40183698, 0.13731001, 0.78305494, 0.168808

Out[1:3]: 
array([0.15097069, 0.96799008, 0.90433337, 0.21950289, 0.57417891,
       0.83993841, 0.0338519 , 0.60969162, 0.21277261, 0.36746915,
       0.58006453, 0.95782836, 0.06913984, 0.48054109, 0.03943768,
       0.53485378, 0.17024108, 0.39016114, 0.3032429 , 0.59717026,
       0.6195952 , 0.74739663, 0.51109144, 0.51984986, 0.40936665,
       0.50869814, 0.05184536, 0.66581264, 0.32761069, 0.1069727 ,
       0.60221112, 0.11830329, 0.17099437, 0.37450236, 0.52621244,
       0.70219119, 0.07885314, 0.60172685, 0.16604509, 0.27418819,
       0.6833549 , 0.56679409, 0.32508641, 0.13289315, 0.57794145,
       0.53203126, 0.27248008, 0.40845894, 0.70279841, 0.02186437,
       0.02009193, 0.76065383, 0.87637614, 0.61036414, 0.56506616,
       0.74523338, 0.65439197, 0.14413614, 0.65375262, 0.84465649,
       0.50204676, 0.98388033, 0.61944139, 0.09393381, 0.09840338,
       0.29346045, 0.16684462, 0.2561784 , 0.70710532, 0.14375477,
       0.97797862, 0.95090953, 0.27078543, 0.838539

Out[2:3]: 
array([0.75580605, 0.44457249, 0.66296055, 0.5763009 , 0.5336001 ,
       0.09211308, 0.8666632 , 0.72655596, 0.39691552, 0.14019258,
       0.80386957, 0.63529589, 0.97642047, 0.49118558, 0.63886886,
       0.40196327, 0.4519691 , 0.99847469, 0.43709988, 0.4739679 ,
       0.65879431, 0.99241883, 0.31178998, 0.93602063, 0.76502998,
       0.64551665, 0.47539325, 0.71845321, 0.71168937, 0.73187933,
       0.14091785, 0.2659907 , 0.88534239, 0.76472887, 0.97460578,
       0.30432413, 0.05843928, 0.9578966 , 0.15988727, 0.43914423,
       0.85840931, 0.7420082 , 0.71794771, 0.48587286, 0.6150354 ,
       0.82431381, 0.3523614 , 0.40341498, 0.97410053, 0.31581322,
       0.93028637, 0.79425248, 0.68846064, 0.15538308, 0.34507984,
       0.47441902, 0.60111973, 0.116086  , 0.63498483, 0.39803268,
       0.97438479, 0.64396968, 0.06979444, 0.09205954, 0.33636288,
       0.45171304, 0.88948989, 0.57140891, 0.45663298, 0.81505007,
       0.44740403, 0.68561932, 0.6162125 , 0.892257

Out[3:3]: 
array([0.27308701, 0.56608611, 0.28412155, 0.31083029, 0.02697815,
       0.01974745, 0.36689794, 0.37779317, 0.84142865, 0.89485416,
       0.26502831, 0.68770387, 0.66686292, 0.57024914, 0.15784981,
       0.55337211, 0.38914072, 0.60127581, 0.84062862, 0.14690358,
       0.87869989, 0.19610135, 0.86508873, 0.62927026, 0.67066837,
       0.24662494, 0.65535735, 0.93262158, 0.13037826, 0.34573321,
       0.93187001, 0.99629717, 0.57879878, 0.76796169, 0.3274121 ,
       0.48720324, 0.11630608, 0.64337018, 0.8945784 , 0.44821235,
       0.538058  , 0.98010901, 0.9739043 , 0.50368536, 0.49675856,
       0.64650253, 0.35526353, 0.30906438, 0.51162869, 0.37436526,
       0.38580468, 0.46420836, 0.36077375, 0.37333186, 0.00877587,
       0.30670874, 0.85199162, 0.09413353, 0.42750839, 0.9658365 ,
       0.49378024, 0.00189782, 0.05876224, 0.14372329, 0.4031532 ,
       0.76877666, 0.60571349, 0.61069276, 0.97066573, 0.57794632,
       0.78741807, 0.17477388, 0.51424145, 0.040010

In [27]:
a = 20 

In [28]:
b = 100

In [29]:
%autopx

%autopx disabled


In [30]:
%pxresult

In [31]:
dview.pull('a')

[20, 20, 20, 20]